include: package:flutter_lints/flutter.yaml
linter:
  rules:
    non_constant_identifier_names: false
    library_names: false
    file_names: false
    prefer_const_constructors: true
    prefer_final_fields: true
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: true
    avoid_print: false
